[paths]
# Path to the specific game folder (should contain world and player data)
Saves       = "/Users/luke/Desktop/7d2d/Practice"
# Path to 7 Days to Die configuration files (XML) 
GameData    = "/Users/luke/Desktop/7d2d/Config"